[SDK-1407] Add Branch QR code methods
BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution pull request #711
Opened 2022-07-26 19:46 UTC by nsingh-branch

### Added a new function, `getBranchQRCode()`, to generate Branch QR codes.
- getBranchQRCode()
    - Takes 4 arguments: QR code settings, universal object,  link properties, and link control parameters.
    - Returns a base64 encoded string of the generated QR code image
    
### Sample Code
```
  function BranchQRCode() {
    var qrCodeSettings = {
        width: 2000,
        codeColor: "#3b2016",
        backgroundColor: "#a8e689",
        centerLogo: "https://cdn.britannica.com/95/156695-131-FF89C9FA/oak-tree.jpg",
        margin: 4,
        imageFormat: "PNG"
    };

    var analytics = {
        channel: "facebook",
        feature: "onboarding",
        campaign: "content 123 launch",
        stage: "new user",
        tags: ["one", "two", "three"],
        alias: document.getElementById("alias").value
      };
    
    var properties = {
        $desktop_url: "http://www.example.com/desktop",
        $android_url: "http://www.example.com/android",
        $ios_url: "http://www.example.com/ios",
        $ipad_url: "http://www.example.com/ipad",
        $deeplink_path: "content/123",
        $match_duration: 2000,
        custom_string: "data",
        custom_integer: Date.now(),
        custom_boolean: true
    };
    
    
    if (branchUniversalObj === null) {
        alert("Need to Generate Branch Universal Object");
        return;
    }
      
    Branch
    .getBranchQRCode(qrCodeSettings, branchUniversalObj, analytics, properties)
    .then(function success(res) {
        document.getElementById("qrCodeImage").src = "data:image/png;base64, " + res;
    })
    .catch(function error(err) {
        alert(err, true);
    });
  }
```

2022-07-28 07:12 UTC, gdeluna-branch commented on src/android/io/branch/BranchSDK.java
> +        if (qrCodeSettings.has("codeColor")) branchQRCode.setCodeColor(qrCodeSettings.getString("codeColor"));
Code style: if statement bodies should always have a new line and be encased in braces. An example of this style is under `createLinkProperties`

2022-07-28 08:50 UTC, gdeluna-branch commented on cordova-ionic-phonegap-branch-deep-linking-attribution.iml
> +<?xml version="1.0" encoding="UTF-8"?>
This is an auto generated file from your environment- I recommend excluding this change then adding *.iml to the .gitignore

2022-07-28 22:01 UTC, gdeluna-branch commented on src/index.js
> +  var args = [];
Does this need to be wrapped in a Promise? There is a network request being made here.
cc @JagadeeshKaricherla-branch

2022-07-30 01:45 UTC, gdeluna-branch requested changes
Awaiting resolution on the Promise

2022-08-03 19:05 UTC, gdeluna-branch approved these changes

2022-08-04 22:23 UTC, JagadeeshKaricherla-branch approved these changes

2022-08-08 22:03 UTC, merged