[SDK-2058] Remove v1/event code
BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution pull request #720
Opened 2023-08-17 22:24 UTC by nsingh-branch

## Reference
SDK-2058 -- Remove v1/event code

## Summary
Removed deprecated v1/events `userCompletedAction` and `sendCommerceEvent` code from `BranchSDK.java`, `BranchSDK.h` and `BranchSDK.m`, and `index.js`, as well as from the sample apps. The changes are published in npm under the alpha package `5.2.1-alpha.0`.

## Motivation
Remove old code that has been deprecated for a sufficient amount of time.

## Type Of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing Instructions
Add the alpha package (`5.2.1-alpha.0`) to your app, or run the examples and ensure all functionality is still working.

cc @BranchMetrics/saas-sdk-devs for visibility.

2023-08-22 17:10 UTC, echo-branch reviewed
Correction, comment was meant for another PR.

2023-09-07 08:21 UTC, gdeluna-branch commented on package.json
> +  "version": "5.2.1-alpha.0",
Remember to revert this

2023-09-07 08:23 UTC, gdeluna-branch commented
Because we're deleting public methods, this seems like a good time to also update the native ios major.

2023-09-07 08:28 UTC, gdeluna-branch requested changes
Revert ver and ticket updating native ios. Please and ty.

2023-09-07 17:55 UTC, nsingh-branch commented
> Revert ver and ticket updating native ios. Please and ty.

@gdeluna-branch Just reverted that package.json change and created a ticket to update the native SDK versions.

2023-09-07 21:22 UTC, gdeluna-branch approved these changes

2023-09-07 21:32 UTC, merged